# Generated by Django 6.0.6 on 2026-07-02 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bigcategory', '0001_initial'),
        ('categories', '0002_category_big_category'),
        ('products', '0002_product_subcategory_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='product',
            name='big_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bigcategory.bigcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
    ]
